services:
  node1:
    build: .
    environment:
      NODE_ADDR: ":3000"
      HTTP_ADDR: ":8080"
      NODE_TCP_PORT: "3000"
      CHAIN_PATH: "/data/chain.json"
      PEER_SEEDS: "node2:8080"
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - node1-data:/data

  node2:
    build: .
    environment:
      NODE_ADDR: ":3000"
      HTTP_ADDR: ":8080"
      NODE_TCP_PORT: "3000"
      CHAIN_PATH: "/data/chain.json"
      PEER_SEEDS: "node1:8080"
    ports:
      - "3001:3000"
      - "8081:8080"
    depends_on:
      - node1
    volumes:
      - node2-data:/data

volumes:
  node1-data:
  node2-data: